name: Test & Deploy Rust Note
run-name: 🚀 Test & Deploy by @${{ github.actor }}
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir bin
          curl -sSL $url | tar -xz --directory=bin
          echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: Run tests
        run: mdbook test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        uses: extractions/setup-crate@v1
        with:
          owner: rust-lang
          name: mdBook
      - name: Generate static content for the book
        run: mdbook build
      - name: list
        run: ls book
      - uses: actions/upload-artifact@v4
        with:
          name: book
          path: book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Download book from build
        uses: actions/download-artifact@v4
        with:
          name: book
          path: book
      - name: list
        run: ls book
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install Vercel CLI
        run: npm install --global vercel
      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        run: vercel book --prod --token=${{ secrets.VERCEL_TOKEN }}
